### ISSUE TITLE
Error running FilterUncorrectablePEfastq.py

### ISSUE THREAD

**Issue by StoltzfusJ** [harvardinformatics/TranscriptomeAssemblyTools#1]
When I run the FilterUncorrectablePEfastq script, I get the following error:
`WorkStation-T3500:/1RNAseq/Programs/TranscriptomeAssemblyTools-master$ python FilterUncorrectabledPEfastq.py -1 /1RNAseq/rCorrector_out/read_1.cor.fq.gz -2 /1RNAseq/rCorrector_out/read_2.cor.fq.gz -o fixed
  File "FilterUncorrectabledPEfastq.py", line 73
    print "%s reads processed" % counter
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s reads processed" % counter)?`

I'm running python v3.6.5

Thanks for any help on getting this script to run.

**Comment by aaronk** [comment]
Pretty sure that code is just python 2.  Adam isn't around right now, but if you could use a python 2 environment, that'll take care of it.

ajk

**Comment by StoltzfusJ** [comment]
Hi Aaron,

Ah, thanks.  Yes, running with python2 works.

Thanks again,

Jonathan

**Comment by StoltzfusJ** [comment]
Yes!  Running python2 takes care of the problem.
