### ISSUE TITLE
UnboundLocalError possibly due to absence of overrepresented sequences in Fastqc

### ISSUE THREAD

**Issue by 000generic** [harvardinformatics/TranscriptomeAssemblyTools#11]
Having run Fastqc, Rcorrector, and  FilterUncorrectabledPEfastq.py on NCBI SRR reads - I am now trying to add in 

RemoveFastqcOverrepSequenceReads.py

but I am getting an UnboundLocalError:

```
python2.7 000-harvard_informatics-RemoveFastqcOverrepSequenceReads.py -1 output/13-harvard/unfixrm_SRR9606759_1.cor.fq.gz -2 output/13-harvard/unfixrm_SRR9606759_2.cor.fq.gz -fql output/8-fastqc/SRR9606759_1_fastqc.zip -fqr output/8-fastqc/SRR9606759_2_fastqc.zip -o output/16-harvard/16-SRR9606759

Traceback (most recent call last):
  File "000-harvard_informatics-RemoveFastqcOverrepSequenceReads.py", line 48, in <module>
    leftseqs=ParseFastqcLog(opts.l_fastqc)
  File "000-harvard_informatics-RemoveFastqcOverrepSequenceReads.py", line 36, in ParseFastqcLog
    return seqs     
UnboundLocalError: local variable 'seqs' referenced before assignment
```

When I check the fastqc text files for overrepresented sequences, it seems like it has none - as overrepresented sequences are only listed as Pass - and no specific reads or sequences are indicated. This is shown below using grep but also I don't see any flags of overrepresented sequences in general or any specific reads or sequences indicated when I read through the text data and summary files:

```
grep 'Overrepresented sequences' output/8-fastqc/SRR9606759_1_fastqc/*txt

output/8-fastqc/SRR9606759_1_fastqc/fastqc_data.txt:>>Overrepresented sequences pass
output/8-fastqc/SRR9606759_1_fastqc/summary.txt:PASS    Overrepresented sequences       SRR9606759_1.fastq
```

I'm wondering if the UnboundLocalError is arising due to the absence of overrepresented sequences in the Fastqc text files. 

If so, it might be useful to update the script FilterUncorrectabledPEfastq.py and have a message sent to its log file that there are no over represented sequences - rather than have script error out.

Or is something else more likely to be going on?

Any ideas or guidance on this would be greatly appreciated!

Thank you :)
Eric

**Comment by adamfreedman** [comment]
I will look into this soon, perhaps I never tested with fastq files without overrepresented sequences! Also, see my other email wrt python 2 vs. 3 for the issue that you closed. everything should be py3 compatible

**Comment by 000generic** [comment]
That would be great - thank you!  

For the different scripts, they only seem to work with Python2 and not Python3. I got them yesterday using:

`git clone https://github.com/harvardinformatics/TranscriptomeAssemblyTools.git
`
see also screenshot

<img width="1600" alt="gitclone" src="https://github.com/harvardinformatics/TranscriptomeAssemblyTools/assets/2045204/78b35cbd-6ec7-426e-af86-c86961f3b807">

**Comment by adamfreedman** [comment]
finally fixed this! also added a small test data set to the repo, incl fastqc reports with and without overrep seqs

**Comment by 000generic** [comment]
Great - thank you :)
