### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by gdamasco** [harvardinformatics/TranscriptomeAssemblyTools#2]
Dear Adam, 

I am trying to use RemoveFastqcOverrepSequenceReads.py and I am getting the following error message. Could you please save me?

python /home/cavender/gdamasco/bin/TranscriptomeAssemblyTools/RemoveFastqcOverrepSequenceReads.py -1 unfixrm_G_11_S4_R1_001.cor_val_1.fq -2 unfixrm_G_11_S4_R2_001.cor_val_2.fq
T**raceback (most recent call last):
  File "/home/cavender/gdamasco/bin/TranscriptomeAssemblyTools/RemoveFastqcOverrepSequenceReads.py", line 46, in <module>
    leftseqs=ParseFastqcLog(opts.l_fastqc)
  File "/home/cavender/gdamasco/bin/TranscriptomeAssemblyTools/RemoveFastqcOverrepSequenceReads.py", line 33, in ParseFastqcLog
    with open(fastqclog) as fp:
TypeError: coercing to Unicode: need string or buffer, NoneType found**

**Comment by sraj214** [comment]
> Dear Adam,
> 
> I am trying to use RemoveFastqcOverrepSequenceReads.py and I am getting the following error message. Could you please save me?
> 
> python /home/cavender/gdamasco/bin/TranscriptomeAssemblyTools/RemoveFastqcOverrepSequenceReads.py -1 unfixrm_G_11_S4_R1_001.cor_val_1.fq -2 unfixrm_G_11_S4_R2_001.cor_val_2.fq
> T**raceback (most recent call last): File "/home/cavender/gdamasco/bin/TranscriptomeAssemblyTools/RemoveFastqcOverrepSequenceReads.py", line 46, in leftseqs=ParseFastqcLog(opts.l_fastqc) File "/home/cavender/gdamasco/bin/TranscriptomeAssemblyTools/RemoveFastqcOverrepSequenceReads.py", line 33, in ParseFastqcLog with open(fastqclog) as fp: TypeError: coercing to Unicode: need string or buffer, NoneType found**

Did you solve this issue ? I am new to bioinfomatics and have been following the same pipeline for Denovo-sequencing and I have the exact error as yours while running this script.

**Comment by adamfreedman** [comment]
as best as i can tell, you never provided as arguments (via -fql and -fqr) the text files output by fastqc. that is whether the over-represented sequences come from. sorry for the very late reply to this. working on updating this script today ... so stay tuned for a new version
