### ISSUE TITLE
Error running FilterUncorrectabledPEfastq.py

### ISSUE THREAD

**Issue by apark21999** [harvardinformatics/TranscriptomeAssemblyTools#7]
Hello,

I would appreciate any help that I can get. I saw a previous issue that I need to run FilterUncorrectabledPEfastq.py under python version 2.7. However, I am still running into this error when using python2.7.
`File "FilterUncorrectabledPEfastq.py", line 75
    print "%s reads processed" % counter
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s reads processed" % counter)?
`
Thank you for your help.

**Comment by matevzl533** [comment]
I got the same error under python3. Are you sure you are running it under python2.7? Here is the original code translated to python3, it seems to work the same, as the original code under pythonr2.7:
[FilterUncorrectabledPEfastq.py.zip](https://github.com/harvardinformatics/TranscriptomeAssemblyTools/files/11304542/FilterUncorrectabledPEfastq.py.zip)

**Comment by tatyanalivshultz** [comment]
Hi:
@apark21999 @matevzl533  The script was written with Python 2 and the syntax has changed for Python 3. To get the script to run I changed the following:
line 75     print("%s reads processed" % counter)
line 78              head2,seq2,placeholder2,qual2=[j.strip() for j in next(R2)]
line 46     return zip_longest(fillvalue=fillvalue, *args)  
line 27  from itertools import zip_longest

Now my script runs but it only writes out the file of R2 reads, not R1 reads!  I'm going to investigate some of the forks to see if anyone else has fixed this.

**Comment by adamfreedman** [comment]
Admittedly, I have not been on top of the emerging issues, including a pull request from a while back. I will be revamping things for python3 very soon.


Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________

**Comment by tatyanalivshultz** [comment]
@adamfreedman Thanks! That would be great! Just FYI the code ran fine under Python 3.9.16 with my four changes. I'm getting both the R1 and R2 reads. I think the problem I encountered was because I had neglected to delete an empty output file from a previous run and the script would not overwrite it. A warning/alert worth adding to the new version!

**Comment by matevzl533** [comment]
@tatyanalivshultz Great info - I have made the same changes in the script I posted in my previous comment. Nice to have confirmation that the script was changed correctly. 

Both sets of corrections differ only in line 78, where I used the `__next__()` function instead of `next()`.

In addition, I have made an additional change in lines 107-113 using the `with` statement that simplifies the code and closing of files:

From:
 ```
unfix_log = open(os.path.join(
        output_dir, "rmunfixable_{}.log".format(opts.id)), 'w')
    unfix_log.write('total PE reads:%s\nremoved PE reads:%s\nretained PE reads:%s\nR1 corrected:%s\nR2 corrected:%s\npairs corrected:%s\nR1 unfixable:%s\nR2 unfixable:%s\nboth reads unfixable:%s\n' % (counter,total_unfixable,total_retained,r1_cor_count,r2_cor_count,pair_cor_count,unfix_r1_count,unfix_r2_count,unfix_both_count))
            
    r1out.close()
    r2out.close() 
    unfix_log.close()
```

To:
```
with open('rmunfixable_%s.log' % opts.id,'w') as unfix_log:
    unfix_log.write('total PE reads:%s\nremoved PE reads:%s\nretained PE reads:%s\nR1 corrected:%s\nR2 corrected:%s\npairs corrected:%s\nR1 unfixable:%s\nR2 unfixable:%s\nboth reads unfixable:%s\n' % (counter,total_unfixable,total_retained,r1_cor_count,r2_cor_count,pair_cor_count,unfix_r1_count,unfix_r2_count,unfix_both_count))

r1out.close()
r2out.close() 
```

**Comment by adamfreedman** [comment]
updated to handle some issues wrt iteration over input files, and removed the "cor" string from the output files ... and added gzipping of output files
