### ISSUE TITLE
updated FilterUncorrectabledPEfastq.py has "cor" in headings

### ISSUE THREAD

**Issue by tatyanalivshultz** [harvardinformatics/TranscriptomeAssemblyTools#9]
Hi @adamfreedman:

Thank you for the updated script. It ran perfectly. However, when I looked at the unfixrm_*.fq files, I saw:

@LH00150:7:223HJHLT3:3:1103:12669:20195 1:N:0:ATCATGCG+ATAGAGCG **l:14053 m:16316 h:18561 cor**
AACAAGGACAAAGGTTCCAATGATCTCAGCACCAAGACCATCTCCTTTGGTGTAGCCGGGGTTCACAAAGTTGGCTCCACCGTTAAGTCTCTCATATGGTCCCTTCTGGAAACCCTTGACAATTCCAGCACCACAGATGGCTCCTAGGCAT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF#FFFFFFFFFFFFFFFFFFFFFFFFF#FF#FFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

The bold string was not there in previous Python2 code after I translated it to Python3. 
With best regards,
Tanya

**Comment by adamfreedman** [comment]
Pretty sure I removed the line that re-wrote the header lines so as to remove the bold-faced section.  The best check is to make sure the same read ids are the retained reads. I can try and check that tomorrow.

Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________
From: tatyanalivshultz ***@***.***>
Sent: Thursday, May 18, 2023 8:38 PM
To: harvardinformatics/TranscriptomeAssemblyTools ***@***.***>
Cc: Freedman, Adam ***@***.***>; Mention ***@***.***>
Subject: [harvardinformatics/TranscriptomeAssemblyTools] updated FilterUncorrectabledPEfastq.py has "cor" in headings (Issue #9)


Hi @adamfreedman<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adamfreedman&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=MITI_LEJgyr1a24IMFAlSaZIPxMpOUT21T7L3fg4CjA&m=TRtftkLWQfb1TM8MLWckmkxPZSaseZS78V142w0MARbvpxOqpZSftGhklgACk3lJ&s=muNxk0BeMq39rB2kosbcocwO9a5CYrpJXoZ3rTZ8bbU&e=>:

Thank you for the updated script. It ran perfectly. However, when I looked at the unfixrm_*.fq files, I saw:

@LH00150:7:223HJHLT3:3:1103:12669:20195 1:N:0:ATCATGCG+ATAGAGCG l:14053 m:16316 h:18561 cor
AACAAGGACAAAGGTTCCAATGATCTCAGCACCAAGACCATCTCCTTTGGTGTAGCCGGGGTTCACAAAGTTGGCTCCACCGTTAAGTCTCTCATATGGTCCCTTCTGGAAACCCTTGACAATTCCAGCACCACAGATGGCTCCTAGGCAT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF#FFFFFFFFFFFFFFFFFFFFFFFFF#FF#FFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

The bold string was not there in previous Python2 code after I translated it to Python3.
With best regards,
Tanya

**Comment by tatyanalivshultz** [comment]
I reran it again today and again the header is not trimmed.
@LH00150:7:223HJHLT3:3:1103:9987:20195 1:N:0:TGTTCCGT+GATGGAGT l:378 m:463 h:543 cor

I used grep -c "@" to count the number of reads in the output unfixrm*.cor.fq and compared them to the output log. The number of retained reads is the same. So the read removal is working but the header trimming is not.

Best regards,
Tanya

**Comment by tatyanalivshultz** [comment]
It looks like lines 94 and 95 in the old code are missing from the updated code. I put them back and the headers are now trimmed correctly. Cheers, Tanya

@LH00150:7:223HJHLT3:3:1103:9525:20195 1:N:0:TGTTCCGT+CCACATTG

                head1=head1.split('l:')[0][:-1] 
                head2=head2.split('l:')[0][:-1]

**Comment by adamfreedman** [comment]
updated to handle some issues wrt iteration over input files, and removed the "cor" string from the output files ... and added gzipping of output files
